### ISSUE TITLE
Замечания по работе #7.2

### ISSUE THREAD

**Issue by Und3rMySk1n** [MUKIVA/web-development#10]
- [x] программа не выводит ошибку, если переданы неправильные данные
- [x] программа падает, если ей передать число в скобке (и вообще падает при некорректном вводе, так как бесконечно выводит ошибку)

```
while (str.indexOf(') (') != -1) {
      str = str.substring(0, str.indexOf(') (')+1);
    }
```
- [x] Непонятен смысл конструкции while.
- [x] `(str[cursor] >= '0' && str[cursor] <= '9') || str[cursor] == '-'` можно вынести в отдельную функцию с говорящим названием
- [x] забыл точки с запятыми в конце выражений

**Comment by MUKIVA** [comment]
Исправлено

**Comment by volgatech-web-development** [comment]
- [ ] не считает выражение `calc(' ( * 2 5 ) ')`. Некорректно работает со скобками.

**Comment by volgatech-web-development** [comment]
- [ ] использовать регулярное выражение на проверку допустимых символов и turnCheck

- [ ] stringFormatting оптимизировать

- [ ] избавиться от вложенности if конструкции в 4 уровня
